project_id = "bkxkvkdqxudabqcsbvbb"

[functions.text-completion]
verify_jwt = false

[functions.image-generation]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false